### ISSUE TITLE
Registering new user returns 500 error

### ISSUE THREAD

**Issue by LaurensRietveld** [the-open-university/basil#42]
But: it seems everything went fine, and I can login without problems

**Comment by enridaga** [comment]
The UI has still some limitations in terms of usability/feedback. Because of that, it is possible that you pressed the sign-up button twice. Thank you for the feedback, we should improve this in https://github.com/the-open-university/pesto
I opened https://github.com/the-open-university/pesto/issues/4

**Comment by enridaga** [comment]
Since this is not about the backend, I close this issue.
