### ISSUE TITLE
do not update the search results when an empty string is given on the search input

### ISSUE THREAD

**Issue by ali1k** [the-open-university/basil#45]
As I see in the UI, when you search with an empty string, it still updates the results! it gets worse when you search for some terms and then want to go back to the main results without clicking the back button in the browser.
My suggestion would be to have a live search without need to click on the search button.

**Comment by enridaga** [comment]
It looks like this is related to the Pesto interface (see https://github.com/the-open-university/pesto).
Yes, this is a bug in the interface.
I am not sure that a live search is really required, particularly because the initial page is not a search result, but is just a list of the latest changed queries. Maybe we should make that more clear.

**Comment by enridaga** [comment]
Fixed in the-open-university/pesto#9
